spring:
  application:
    name: dungeondesk
  datasource:
    url: jdbc:h2:file:./data/dungeondesk;AUTO_SERVER=TRUE
    username: sa
    password: dungeondesk
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        generate_statistics: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG